index/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="index"),

]

tourist_web_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('events/', include('events.urls')),
    path('users/', include('users.urls')),
    path('cities/', include('cities.urls')),
    path('directions/', include('directions.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # для сброса пароля
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="users/reset_password.html"),
         name='reset_password'),
    # для отправления пароля на почту
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name="users/reset_password_sent.html"),
         name='password_reset_done'),
    #   письмо со ссылкой и инструкциями по сбросу
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/reset.html"),
         name='password_reset_confirm'),
    # сообщение об успешном сбросе пароля
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name="users/reset_password_complete.html"),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('profile_form/', views.profile_form, name='profile_form'),
    path('create_place/', views.create_place, name='create_place'),
    path('travel_diary/', views.travel_diary, name='travel_diary'),
    path('place/<str:pk>/', views.place, name='place'),
    path('verify/<str:email>/<uuid:code>/', views.VerificationView.as_view(), name='verification'),
]

users/models.py
from datetime import date
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.timezone import now


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Пользователь")
    name = models.CharField(max_length=50, null=True, blank=True, verbose_name="Имя")
    email = models.EmailField(max_length=100, null=True, blank=True, verbose_name="Почта")
    username = models.CharField(max_length=50, null=True, blank=True, verbose_name="Логин")
    my_city = models.CharField(max_length=50, null=True, blank=True, verbose_name="Мой город")
    profile_image = models.ImageField(upload_to="profiles/", default="profiles/notphoto.jpg", verbose_name="Фото")
    bio = models.TextField(null=True, blank=True, verbose_name="О себе")
    verify = models.BooleanField(default=False, verbose_name="Подтверждение почты")

    def __str__(self):
        return str(f"Пользователь {self.username}")

    class Meta:
        ordering = ['name']
        verbose_name = "профиль"
        verbose_name_plural = "Профили"


class Verification(models.Model):
    code = models.UUIDField(unique=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    expiration = models.DateTimeField()

    def __str__(self):
        return f"Verification object for {self.user.email}"

    def send_verification_email(self):
        link = reverse('verification', kwargs={'email': self.user.email, 'code': self.code})
        verification_link = f'{settings.DOMAIN_NAME}{link}'
        subject = f'Подтверждение учетной записи для {self.user.username}'
        message = f'Для подтверждения учетной записи {self.user.email} перейдите по ссылке {verification_link}'

        try:
            send_mail(
                subject,
                message,
                settings.EMAIL_HOST_USER,
                [self.user.email]
            )
        except BadHeaderError:
            return HttpResponse("Обнаружен неверный заголовок!")

    def is_expired(self):
        return True if now() >= self.expiration else False

    class Meta:
        verbose_name = 'верификацию'
        verbose_name_plural = 'Верификация по почте'


class Places(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, verbose_name="Пользователь")
    location = models.CharField(max_length=100, null=True, blank=True, verbose_name="Локация")
    experience = models.TextField(null=True, blank=True, verbose_name="Впечатление")
    place_image = models.ImageField(upload_to="places/", default="places/window.jpg", verbose_name="Фото")
    creates = models.DateTimeField(auto_now_add=True, verbose_name="Дата")

    def __str__(self):
        return str(f"{self.location}")

    class Meta:
        verbose_name = "локацию"
        verbose_name_plural = "Локации"


class TravelDiary(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="Кто создал")
    place = models.CharField(max_length=100, verbose_name="Место отдыха")
    arrival_date = models.DateField(auto_now=False, blank=True, null=True, verbose_name="Когда приехали?")
    departure_date = models.DateField(auto_now=False, blank=True, null=True, verbose_name="Когда уехали?")
    tickets_to_and_from = models.DecimalField(max_digits=8, decimal_places=0, default=0, verbose_name="Стоимость билетов туда и обратно")
    cafes = models.TextField(null=True, blank=True, verbose_name="Кафе и рестораны")
    housing = models.CharField(max_length=100, verbose_name="Где остановились?")
    entertainments = models.TextField(null=True, blank=True, verbose_name="Развлечения")
    transportation_costs = models.DecimalField(max_digits=8, decimal_places=0, default=0, verbose_name="Потрачено на транспорт")
    travel_image = models.ImageField(upload_to="travels/", default="travels/window.jpg", verbose_name="Фото")
    money_spend_on_eats = models.DecimalField(max_digits=8, decimal_places=0, default=0, verbose_name="Потрачено на еду")
    money_spend_on_housing = models.DecimalField(max_digits=8, decimal_places=0, default=0, verbose_name="Потрачено на жилье")
    money_spend_on_entertainments = models.DecimalField(max_digits=8, decimal_places=0, default=0, verbose_name="Потрачено на развлечения")

    def sum(self):
        return self.tickets_to_and_from + self.transportation_costs + self.money_spend_on_eats + self.money_spend_on_entertainments + self.money_spend_on_housing

    def diff_date(self):
        start = date.fromisoformat(str(self.arrival_date))
        end = date.fromisoformat(str(self.departure_date))
        self.delta = end - start
        return self.delta

    def __str__(self):
        return str(f"{self.place}")

    class Meta:
        verbose_name = "путешествие"
        verbose_name_plural = "Дневник путешествий"


class MorePhoto(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, verbose_name="Кто создал")
    place = models.ForeignKey(TravelDiary, on_delete=models.CASCADE, verbose_name="Путешествие")
    add_more_photo = models.ImageField(upload_to="travels/add/", blank=True, null=True, verbose_name="Изображение")

    def __str__(self):
        return str(f"+1 фото для {self.place}")

    class Meta:
        verbose_name = "ещё изображение"
        verbose_name_plural = "Ещё изображения"

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.forms import ModelForm
from django import forms
import uuid
from datetime import timedelta
from django.utils.timezone import now


class TravelDiaryForm(ModelForm):
    class Meta:
        model = TravelDiary
        fields = '__all__'
        exclude = ['owner', ]
        widgets = {'arrival_date': forms.DateInput(format='%Y-%m-%d', attrs={"class": "input__group", "type": "date"}),
                   'departure_date': forms.DateInput(format='%Y-%m-%d', attrs={"class": "input__group", "type": "date"})
                   }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "input__group"})


class AddMorePhotoForm(ModelForm):
    class Meta:
        model = MorePhoto
        fields = ['add_more_photo']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "form-control mb-3"})


class PlaceForm(ModelForm):
    class Meta:
        model = Places
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({"class": "input__group"})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'username', 'bio', 'my_city',
                  'profile_image']

    def save(self, commit=True):
        user = super().save(commit=True)
        expiration = now() + timedelta(hours=24)
        record = Verification.objects.create(code=uuid.uuid4(), user=user, expiration=expiration)
        record.send_verification_email()
        return user

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.http import HttpResponse
from django.views.generic.base import TemplateView


def login_user(request):
    if request.user.is_authenticated:
        return redirect("profile")

    if request.method == "POST":
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except ObjectDoesNotExist:
            messages.error(request,"Пользователь с таким именем не найден!")

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("profile")
        else:
            messages.error(request,"Допущена ошибка при вводе имени или пароля!")
            return redirect("index")

    return render(request, "events/base.html")


def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, "Аккаунт успешно создан! "
                                      "Заполните полностью свой профиль - нажав на фото!")
            login(request, user)
            return redirect('profile')
        else:
            messages.error(request, "Допущена ошибка при регистрации!")
            return redirect("index")

    form = RegisterUserForm
    context = {'form': form}
    return render(request, "users/register.html", context)


def logout_user(request):
    logout(request)
    messages.info(request, "Вы вышли из своего аккаунта!")
    return redirect('index')


@login_required(login_url='index')
def profile(request):
    prof = request.user.profile
    place = prof.traveldiary_set.all()
    form = ProfileForm(instance=prof)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=prof)
        if form.is_valid():
            form.save()

            return redirect('profile')
    context = {
        "profile": prof,
        "places": place,
        'form': form,
    }

    return render(request, "users/profile.html", context)


def profile_form(request):
    prof = request.user.profile
    form = ProfileForm(instance=prof)

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=prof)
        if form.is_valid():
            form.save()
            messages.error(request, "Перейдите на свою почту, чтобы пройти верификацию! Сообщение может быть в спаме!")
            return redirect('profile')

    context = {'form': form}
    return render(request, "users/profile_form.html", context)


class VerificationView(TemplateView):
    template_name = 'users/verification.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Путешествия по России - Подтверждение почты"
        return context

    def get(self, request, *args, **kwargs):
        code = kwargs['code']
        user = Profile.objects.get(email=kwargs['email'])
        verifications = Verification.objects.filter(user=user, code=code)
        if verifications.exists() and not verifications.first().is_expired():
            user.verify = True
            user.save()
            return super().get(request, *args, **kwargs)
        else:
            return redirect('index')


def create_place(request):
    prof = request.user.profile
    form_place = TravelDiaryForm()

    if request.method == "POST":
        form_place = TravelDiaryForm(request.POST, request.FILES)
        if form_place.is_valid():
            place = form_place.save(commit=False)
            place.owner = prof
            place.save()
            return redirect('travel_diary')

    context = {'form_place': form_place}
    return render(request, 'users/create_place.html', context)


def travel_diary(request):
    prof = request.user.profile
    place = prof.traveldiary_set.all()
    form_place = TravelDiaryForm()

    if request.method == "POST":
        form_place = TravelDiaryForm(request.POST, request.FILES)
        if form_place.is_valid():
            place = form_place.save(commit=False)
            place.owner = prof
            place.save()
            return redirect('travel_diary')

    context = {
        "profile": prof,
        "places": place,
        'form_place': form_place
    }

    return render(request, 'users/travel_diary.html', context)


def place(request, pk):
    prof = request.user.profile
    place = TravelDiary.objects.get(id=pk)
    form_photo = AddMorePhotoForm()

    if request.method == 'POST':
        form_photo = AddMorePhotoForm(request.POST, request.FILES)
        if form_photo.is_valid():
            photo = form_photo.save(commit=False)
            photo.owner = prof
            photo.place = place
            photo.save()
        else:
            form_photo = AddMorePhotoForm()
    context = {
        'place': place,
        'form_photo': form_photo
    }

    return render(request, 'users/specific_place.html', context)

users/templates/users/create_place.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content book_form">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Добавить путешествие</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action="{%url 'create_place'%}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}

        {%for field in form_place%}
          <div class="mb-3">
            <div class="input__row">
                <div class="input__group">
                    {{field}}
                    <label class="label_text">{{field.label}}: </label>
                </div>
            </div>
          </div>
        {%endfor%}
        <button class="book_btn">Готово</button>

    </form>
</div>
  </div>
</div>

users/templates/users/login.html
{%extends 'events/base.html'%}
{% load static %}
{%block content%}

<div class="log-wrapper">
      <span class="icon-close">
        <ion-icon name="close"></ion-icon>
      </span>
      <div class="form-box login">
        <h2>Вход</h2>
        <form action="{%url 'login'%}" method="post">
          {%csrf_token%}

          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="text" name="username" required>
            <label>Имя</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password" required>
            <label>Пароль</label>
          </div>
          <div class="remember-forgot">
            <label><input type="checkbox">Запомнить</label>
            <a href="#">Забыли пароль?</a>
          </div>
          <button type="submit" class="btn">Войти</button>
          <div class="login-register">
            <p>Ещё нет аккаунта?
              <a href="#" class="register-link">Зарегистрируйтесь!</a>
            </p>
          </div>
        </form>
      </div>
</div>
{%endblock%}

users/templates/users/popup_log_reg.html
{% load static %}

    <div class="log-wrapper">
      <span class="icon-close">
        <ion-icon name="close"></ion-icon>
      </span>
      <div class="form-box login">
        <h2>Вход</h2>
        <form action="{%url 'login'%}" method="post">
          {%csrf_token%}

          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="text" name="username" required>
            <label>Имя</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password" required>
            <label>Пароль</label>
          </div>
          <div class="remember-forgot">
            <a href="{%url 'reset_password'%}">Забыли пароль?</a>
          </div>
          <button type="submit" class="btn-popup-auth">Войти</button>
          <div class="login-register">
            <p>Ещё нет аккаунта?
              <a href="#" class="register-link">Зарегистрируйтесь!</a>
            </p>
          </div>
        </form>
      </div>


      <div class="form-box register">
        <h2>Регистрация</h2>
        <form action="{%url 'register'%}" method="post">
          {%csrf_token%}

          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="text" name="username" required>
            <label>Имя</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="email" name="email" required>
            <label>Почта</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password1" required>
            <label>Пароль</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password2" required>
            <label>Повторите пароль</label>
          </div>

          <button type="submit" class="btn-popup-auth">Зарегистироваться</button>
          <div class="login-register">
            <p>Уже есть аккаунт?
              <a href="#" class="login-link">Войти</a>
            </p>
          </div>
        </form>
      </div>

    </div>

users/templates/users/profile.html
{%extends 'events/base.html'%}
{% load static %}
{%block content%}
<main data-barba="container" data-barba-namespace="home">

<div class="header_wrapper">

        <div class="hd-photo p-4 mb-4 text-body-emphasis">
    <div class="hd">
      <h1>Россия твоими глазами</h1>
      <br>
      <p>
        Личный дневник путешественника поможет тебе составить уникальный маршрут и не забыть самое важное - впечатления!</p>
    </div>
  </div>

    <div class="cols_container">
        <div class="left_col">
            <a class="btn text-decoration-none" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" href="#">
<!--            <a class="link-body-emphasis text-decoration-none" href="{%url 'profile_form'%}">-->
            <div class="img_container">
                <img src="{{profile.profile_image.url}}" alt="user">
            </div>
              </a>
            <h2>{{profile.name}}</h2>
            <p>{{profile.my_city}}</p>
            <p>{{user.email}}</p>
            <div class="about">
                <p>{{profile.bio}}</p>
                {%for place in places.all%}
                <ul>
                    <li>
                        <a class="place-popup text-decoration-none" href="{%url 'place' place.id%}">{{place.place}}</a>
                    </li>
                </ul>
                {%endfor%}
            </div>
        </div>
        <div class="right_col">
            <nav>
                <ul>
                    <li><a href="{%url 'travel_diary'%}">Мои путешествия</a></li>
                </ul>
            </nav>


            <div class="photos">
                <div id="map-test" class="map"></div>
            </div>

        </div>
    </div>
</div>


{% include 'users/profile_form.html' %}
</main>
{%endblock%}

users/templates/users/profile_form.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content book_form">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Изменение профиля</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <form action="{%url 'profile_form'%}" method="POST" enctype="multipart/form-data">
            {%csrf_token%}
          <div class="mb-3">
              {%for field in form%}
            <div class="modal-body">
                <div class="input__group">
                    {{field}}
                    <label class="col-form-label">{{field.label}}: </label>
                </div>
            </div>
              {%endfor%}
            <input class="book_btn" type="submit" value="Готово" />
          </div>
        </form>
    </div>
  </div>
</div>

users/templates/users/register.html
{%extends 'events/base.html'%}
{% load static %}
{%block content%}

<div class="log-wrapper">
      <span class="icon-close">
        <ion-icon name="close"></ion-icon>
      </span>
<div class="form-box register">
        <h2>Регистрация</h2>
        <form action="{%url 'register'%}" method="post">
          {%csrf_token%}

          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="text" name="username" required>
            <label>Имя</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="person"></ion-icon>
            </span>
            <input type="email" name="email" required>
            <label>Почта</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password1" required>
            <label>Пароль</label>
          </div>
          <div class="input-box">
            <span class="icon">
              <ion-icon name="key-outline"></ion-icon>
            </span>
            <input type="password" name="password2" required>
            <label>Повторите пароль</label>
          </div>

          <button type="submit" class="btn">Зарегистироваться</button>
          <div class="login-register">
            <p>Уже есть аккаунт?
              <a href="#" class="login-link">Войти</a>
            </p>
          </div>
        </form>
      </div>

    </div>

{%endblock%}

users/templates/users/reset.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Путешествуй!</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style_cities.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tourstyle.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style_maps.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    <link rel="icon" href="{% static 'images/russiaa.png' %}">
</head>
<body>
{%block content%}
<div class="book_tour">
    <form class="book_form" method="post">
            {%csrf_token%}
        <h1>Создайте новый пароль</h1>
         <div class="input__row">
            <div class="input__group">
                <label for="">Придумайте пароль</label>
                <br>
                <h4>{{form.new_password1}}</h4>
            </div>
         </div>
        <div class="input__row">
             <div class="input__group">
                <label for="">Повторите пароль</label>
                <br>
                <h4>{{form.new_password2}}</h4>
            </div>
        </div>

        <input type="submit" class="book_btn" value="Готово">
    </form>
</div>

{%endblock%}

</body>
</html>

users/templates/users/reset_password.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Путешествуй!</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style_cities.css' %}" />
    <link rel="stylesheet" href="{% static 'css/tourstyle.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style_maps.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@4.2.0/fonts/remixicon.css" rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css">
    <link rel="icon" href="{% static 'images/russiaa.png' %}">
</head>
<body>
{%block content%}
<div class="book_tour">
    <form class="book_form" method="post">
            {%csrf_token%}
        <h1>Восстановление пароля</h1>

        <div class="input__row">
            <div class="input__group">
                <label for="">Введите адрес электронной почты, указанный при регистрации</label>
                <br>
                <h4>{{form.email}}</h4>
            </div>
        </div>
        <input type="submit" class="book_btn" value="Готово">
    </form>
</div>

{%endblock%}

</body>
</html>

users/templates/users/specific_place.html
{%extends 'events/base.html'%}
{% load static %}
{%load humanize%}
{%block content%}
<main data-barba="container" data-barba-namespace="home">

  <div class="hd-photo p-4 mb-4 text-body-emphasis">
    <div class="hd">
      <h1>Россия твоими глазами</h1>
    </div>
  </div>
<!--о городе-->
<section class="city" id="city">
    <div class="image-city">
        <a data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@mdo" href="#"><img src="{{ place.travel_image.url }}" alt=""></a>
    </div>

    <div class="city-content">
        <a href="{%url 'profile'%}">
            <h3>{{place.place}}</h3>
        </a>
    </div>

    <p>Приехали <i>{{place.arrival_date}}</i> и остановились на ночлег в месте с названием <i>"{{place.housing}}"</i>, где за <i>{{place.diff_date|cut:"days, 0:00:00"}}</i> суток заплатили <i>{{place.money_spend_on_housing|intcomma}}</i> рублей.
        Попробовали местную кухню в следующих заведениях: <i>{{place.cafes}}</i>.
        За все путешествие на еду потратили примерно <i>{{place.money_spend_on_eats|intcomma}}</i> рублей.
        Развлекались и интересно проводили время в таких местах как: <i>{{place.entertainments}}</i>, потратив на все это около <i>{{place.money_spend_on_entertainments|intcomma}}</i> рублей.
        В течение самого путешествия на транспорт было потрачено около <i>{{place.transportation_costs|intcomma}}</i> рублей, а на билеты туда и обратно <i>{{place.tickets_to_and_from|intcomma}}</i> рублей.
        Домой уехали <i>{{place.departure_date}}</i>.
    </p>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">

        <div class="modal-content form-photo">
            <form action="{%url 'place' place.id%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <h1>Добавьте ещё фото из этого путешествия</h1>

                {{ form_photo.add_more_photo }}
                <button type="submit" class="btn btn-outline-success">Добавить</button>
            </form>
        </div>
      </div>
    </div>
    <h1>/ <b>Итого было потрачено: {{place.sum|intcomma}} рублей</b></h1>
</section>

<section class="tour-carosel">
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner">
    {%for img in place.morephoto_set.all%}
    <div class="carousel-item active data-bs-interval='500'">
      <img src="{{img.add_more_photo.url}}" class="d-block w-100" alt="...">
    </div>
    {%endfor%}

  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</section>
    <br>
    <br>
    <br>
</main>


{%endblock%}